### PR TITLE
Added ru_ru.json

### PR DESCRIPTION
**Pull request by Felix14-v2**

### CODE REVIEW

**Comment by replaceitem** [comment]
Nice, thank you!

**Comment by replaceitem** [comment]
@Felix14-v2 I added some more texts in the last few commits, would you mind adding those too?
Sorry for bothering you by changing existing texts to translatables, but i figured rather do it now than later.

**Comment by Felix14-v2** [comment]
Sorry for the long answer, I hurt my head and couldn't work at all for a while. I'll do it as soon as I can.

**Comment by replaceitem** [comment]
No worries, if you don't have time thats fine.

**Pull request merged**
